baseurl = "https://ivan-bocharov.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Ivan Bocharov"
title = "P(kek) = 1.0"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "My personal website"
copyright = "Copyright © 2017 Ivan Bocharov"
logofile = "img/plaid.jpg"
faviconfile = "img/plaid.jpg"
highlightjs = true
progressively = true
latestpostcount = 5
github = "ivan-bocharov"
email = "i.a.bocharov _at_ tue.nl"
twitter = "example"
social_banner = "img/banner.png"